# Generated by Django 6.1.1 on 2026-09-12 18:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=80)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('icp_countries', models.CharField(blank=True, help_text='Comma-separated ISO country codes.', max_length=120)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL)),
                ('icp_topics', models.ManyToManyField(blank=True, related_name='brands', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('objective', models.CharField(choices=[('awareness', 'Brand awareness'), ('pipeline', 'Pipeline and leads'), ('signups', 'Product signups'), ('hiring', 'Employer brand')], default='pipeline', max_length=20)),
                ('pricing_model', models.CharField(choices=[('flat', 'Flat fee per post'), ('cpc', 'Cost per qualified click')], default='flat', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('product_description', models.TextField(blank=True)),
                ('key_messages', models.TextField(blank=True)),
                ('guidelines', models.TextField(blank=True)),
                ('dos', models.TextField(blank=True)),
                ('donts', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('landing_url', models.URLField(blank=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('headline', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('country', models.CharField(default='FR', max_length=2)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('median_views', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('price_per_post', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(related_name='creators', to='core.topic')),
            ],
            options={
                'ordering': ['-followers'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('draft', 'Draft ready'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='invited', max_length=12)),
                ('draft_content', models.TextField(blank=True)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('post_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.creator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('pipeline_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.booking')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Wallet top-up'), ('charge', 'Campaign charge'), ('payout', 'Creator payout')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('campaign', 'creator'), name='unique_creator_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='postmetric',
            constraint=models.UniqueConstraint(fields=('booking', 'date'), name='unique_metric_per_booking_day'),
        ),
    ]
